### ISSUE TITLE
Stream.js does not work when required via node

### ISSUE THREAD

**Issue by abdulapopoola** [abdulapopoola/Stream#2]
> require('stream-js')()
> TypeError: Cannot read property 'initConfig' of undefined
>     at module.exports (C:\Users\ja27264\node_modules\stream-js\gruntfile.js:4:10)
>     at repl:1:21
>     at REPLServer.defaultEval (repl.js:248:27)
>     at bound (domain.js:280:14)
>     at REPLServer.runBound [as eval](domain.js:293:12)
>     at REPLServer.<anonymous> (repl.js:412:12)
>     at emitOne (events.js:82:20)
>     at REPLServer.emit (events.js:169:7)
>     at REPLServer.Interface._onLine (readline.js:210:10)
>     at REPLServer.Interface._line (readline.js:549:8)

**Comment by isocroft** [comment]
Hi @abdulapopoola, I have looked into this bug and i can tell you that the problem is from both the "stream.js" file and the "package.json" file. I will send in a PR soon with all my fixes for this bug for a merge.

On the side, i am very excited about this project of yours and i have a project call *phlorx* which i will like to channel this great work of yours to. We can have discussions on this later if you will.

Thanks!

**Comment by abdulapopoola** [comment]
Thanks a lot @isocroft! Would love to collaborate and make this much better!!
